apiVersion: v1
kind: ConfigMap
metadata:
  name: libreddit-nginx-conf
  labels:
    app: libreddit
data:
  nginx.conf: |-
    user nginx;
    worker_processes 1;
    events {
      worker_connections 10240;
    }
    http {
      server {
        location / {
            proxy_http_version 1.1;
            proxy_pass http://127.0.0.1:8080;
        }
      }
    }

